// Generated by scripts/generate-reel-icons.mjs from the pinned Lucide package.
// Lucide ISC license: assets/reel-icons/LICENSE.
export const reelIconAssets: Record<string, number> = {
  "Heart|30|#ffffff|none|2.2|true": require('../assets/reel-icons/heart-ffffff-shadow.png'),
  "Heart|30|#ff3b64|#ff3b64|2.2|true": require('../assets/reel-icons/heart-ff3b64-shadow.png'),
  "Heart|30|rgba(255,255,255,0.5)|none|2.2|true": require('../assets/reel-icons/heart-rgba25525525505-shadow.png'),
  "MessageCircle|30|#ffffff|none|2.2|false": require('../assets/reel-icons/message-circle-ffffff-plain.png'),
  "Share|28|#ffffff|none|2.2|true": require('../assets/reel-icons/share-ffffff-shadow.png'),
  "Share2|28|#ffffff|none|2.2|true": require('../assets/reel-icons/share-2-ffffff-shadow.png'),
  "Ellipsis|28|#ffffff|none|2.2|true": require('../assets/reel-icons/ellipsis-ffffff-shadow.png'),
  "FileText|26|#ffffff|none|2.2|false": require('../assets/reel-icons/file-text-ffffff-plain.png'),
  "Repeat2|26|#050505|none|2.2|false": require('../assets/reel-icons/repeat-2-050505-plain.png'),
  "Globe|26|#050505|none|2.2|false": require('../assets/reel-icons/globe-050505-plain.png'),
  "Globe|26|#ffffff|none|2.2|false": require('../assets/reel-icons/globe-ffffff-plain.png'),
  "WandSparkles|26|#67d6a7|none|2.2|false": require('../assets/reel-icons/wand-sparkles-67d6a7-plain.png'),
  "LockKeyhole|26|#f2b95e|none|2.2|false": require('../assets/reel-icons/lock-keyhole-f2b95e-plain.png'),
};
