begin;

create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;

select plan(22);

insert into auth.users (id, email, aud, role, raw_app_meta_data, raw_user_meta_data)
values
  ('51000000-0000-4000-8000-000000000001'::uuid, 'search-creator@example.invalid',
   'authenticated', 'authenticated', '{}'::jsonb, '{}'::jsonb),
  ('52000000-0000-4000-8000-000000000002'::uuid, 'search-viewer@example.invalid',
   'authenticated', 'authenticated', '{}'::jsonb, '{}'::jsonb);

update public.profiles
set username = 'luna-studio', display_name = 'Luna Studio', bio = 'Cinematic product artist'
where id = '51000000-0000-4000-8000-000000000001'::uuid;

insert into public.posts (
  id, user_id, visibility, category, source_kind, post_format, review_status,
  title, body, prompt, source_tool, source_tool_slug, showcase_asset_path, created_at, updated_at
) values
  (
    '51000000-0000-4000-8000-000000000010'::uuid,
    '51000000-0000-4000-8000-000000000001'::uuid,
    'public', 'image', 'magicbooklet', 'media', 'visible',
    'Celestial product reveal', 'A premium campaign frame', 'Soft orbit lighting',
    'Nano Banana', 'nano-banana', 'showcase/search-public.png', now(), now()
  ),
  (
    '51000000-0000-4000-8000-000000000011'::uuid,
    '51000000-0000-4000-8000-000000000001'::uuid,
    'public', 'image', 'magicbooklet', 'media', 'hidden',
    'Hidden campaign', 'This must never be indexed', null,
    null, null, 'showcase/search-hidden.png', now(), now()
  ),
  (
    '51000000-0000-4000-8000-000000000012'::uuid,
    '51000000-0000-4000-8000-000000000001'::uuid,
    'private', 'image', 'magicbooklet', 'media', 'visible',
    'Private campaign', 'This must never be indexed', null,
    null, null, 'showcase/search-private.png', now(), now()
  );

select is(
  (select count(*)::bigint from public.post_search_documents
   where creator_user_id = '51000000-0000-4000-8000-000000000001'::uuid),
  1::bigint,
  'only moderation-visible public posts are indexed'
);

select is(
  (select public_post_count from public.creator_search_documents
   where creator_user_id = '51000000-0000-4000-8000-000000000001'::uuid),
  1,
  'creator documents maintain the public visible post count'
);

select is(
  (select count(*)::bigint from public.search_public_creators('luna', null, null, null, 20)
   where creator_user_id = '51000000-0000-4000-8000-000000000001'::uuid),
  1::bigint,
  'creator search matches a username prefix'
);

select is(
  (select count(*)::bigint from public.search_public_creators('cinematic artist', null, null, null, 20)
   where creator_user_id = '51000000-0000-4000-8000-000000000001'::uuid),
  1::bigint,
  'creator search matches profile biography terms'
);

select is(
  (select count(*)::bigint from public.search_public_posts('product reveal', null, null, null, 20)
   where post_id = '51000000-0000-4000-8000-000000000010'::uuid),
  1::bigint,
  'post search matches title terms'
);

select is(
  (select count(*)::bigint from public.search_public_posts('nano banana', null, null, null, 20)
   where post_id = '51000000-0000-4000-8000-000000000010'::uuid),
  1::bigint,
  'post search matches source tools'
);

update public.posts
set title = 'Aurora packaging study'
where id = '51000000-0000-4000-8000-000000000010'::uuid;

select ok(
  (select search_text like '%aurora packaging study%'
   from public.post_search_documents
   where post_id = '51000000-0000-4000-8000-000000000010'::uuid),
  'post edits synchronously refresh the search document'
);

update public.posts
set review_status = 'hidden'
where id = '51000000-0000-4000-8000-000000000010'::uuid;

select is(
  (select count(*)::bigint from public.post_search_documents
   where post_id = '51000000-0000-4000-8000-000000000010'::uuid),
  0::bigint,
  'moderation removal deletes the post search document'
);

select is(
  (select public_post_count from public.creator_search_documents
   where creator_user_id = '51000000-0000-4000-8000-000000000001'::uuid),
  0,
  'moderation removal updates creator discovery statistics'
);

select is(
  (select count(*)::bigint from public.creator_search_documents
   where creator_user_id = '52000000-0000-4000-8000-000000000002'::uuid),
  0::bigint,
  'autogenerated empty profiles are excluded from creator discovery'
);

update public.profiles
set username = 'luna', display_name = 'Luna'
where id = '52000000-0000-4000-8000-000000000002'::uuid;

select is(
  (select username from public.search_public_creators('luna', null, null, null, 20) limit 1),
  'luna',
  'an exact username outranks a username prefix match'
);

insert into public.posts (
  id, user_id, visibility, category, source_kind, post_format, review_status,
  title, body, prompt, source_tool, source_tool_slug, showcase_asset_path,
  save_count, created_at, updated_at
) values
  (
    '51000000-0000-4000-8000-000000000013'::uuid,
    '51000000-0000-4000-8000-000000000001'::uuid,
    'public', 'image', 'magicbooklet', 'media', 'visible',
    'Neon dreams', 'A quiet frame', null,
    null, null, 'showcase/search-neon.png', 0, now(), now()
  ),
  (
    '51000000-0000-4000-8000-000000000014'::uuid,
    '51000000-0000-4000-8000-000000000001'::uuid,
    'public', 'image', 'magicbooklet', 'media', 'visible',
    'Campaign archive', 'Neon dreams everywhere in this campaign', null,
    null, null, 'showcase/search-campaign.png', 100000, now(), now()
  );

select is(
  (select post_id from public.search_public_posts('neon dreams', null, null, null, 1) limit 1),
  '51000000-0000-4000-8000-000000000013'::uuid,
  'an exact title match outranks a higher-engagement body match'
);

select is(
  (with first_page as (
     select post_id, search_score
     from public.search_public_posts('neon dreams', null, null, null, 1)
   )
   select count(*)::bigint
   from first_page
   cross join lateral public.search_public_posts(
     'neon dreams', null, first_page.search_score, first_page.post_id, 10
   ) as next_page
   where next_page.post_id = first_page.post_id),
  0::bigint,
  'keyset pages never repeat an id'
);

select is(
  (with first_page as (
     select post_id, search_score
     from public.search_public_posts('neon dreams', null, null, null, 1)
   )
   select count(*)::bigint
   from first_page
   cross join lateral public.search_public_posts(
     'neon dreams', null, first_page.search_score, first_page.post_id, 10
   ) as next_page
   where next_page.post_id = '51000000-0000-4000-8000-000000000014'::uuid),
  1::bigint,
  'the following keyset page continues with the next-ranked post'
);

update public.posts
set archived_at = now()
where id = '51000000-0000-4000-8000-000000000014'::uuid;

select is(
  (select count(*)::bigint from public.post_search_documents
   where post_id = '51000000-0000-4000-8000-000000000014'::uuid),
  0::bigint,
  'archiving a post removes its search document'
);

select is(
  (select count(*)::bigint from public.search_public_creators('%%', null, null, null, 20)),
  0::bigint,
  'LIKE metacharacters in creator queries match literally, not as wildcards'
);

select is(
  (select count(*)::bigint from public.search_public_posts('%%%', null, null, null, 20)),
  0::bigint,
  'ILIKE metacharacters in post queries match literally, not as wildcards'
);

select ok(
  not has_table_privilege('anon', 'public.post_search_documents', 'SELECT')
  and not has_table_privilege('authenticated', 'public.post_search_documents', 'SELECT'),
  'client roles cannot read post search projections directly'
);

select ok(
  not has_function_privilege('anon', 'public.search_public_posts(text,uuid,double precision,uuid,integer)', 'EXECUTE')
  and not has_function_privilege('authenticated', 'public.search_public_posts(text,uuid,double precision,uuid,integer)', 'EXECUTE'),
  'client roles cannot call post search RPCs directly'
);

select ok(
  not has_function_privilege('anon', 'public.search_public_creators(text,uuid,double precision,uuid,integer)', 'EXECUTE')
  and not has_function_privilege('authenticated', 'public.search_public_creators(text,uuid,double precision,uuid,integer)', 'EXECUTE'),
  'client roles cannot call creator search RPCs directly'
);

select has_index(
  'public', 'post_search_documents', 'post_search_documents_vector_idx',
  'post search has a full-text GIN index'
);

select has_index(
  'public', 'creator_search_documents', 'creator_search_documents_username_trgm_idx',
  'creator handles have a trigram GIN index'
);

select * from finish();
rollback;
