BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = public, extensions;
SELECT plan(10);
SELECT has_function('public', 'claim_media_upload_intents_for_reclaim', ARRAY['uuid[]']);
SELECT ok(NOT has_function_privilege('anon', 'public.claim_media_upload_intents_for_reclaim(uuid[])', 'EXECUTE'), 'anonymous callers cannot fence uploads');
SELECT ok(NOT has_function_privilege('authenticated', 'public.claim_media_upload_intents_for_reclaim(uuid[])', 'EXECUTE'), 'authenticated callers cannot fence uploads');
SELECT ok(has_function_privilege('service_role', 'public.claim_media_upload_intents_for_reclaim(uuid[])', 'EXECUTE'), 'service role can coordinate cleanup');
SET LOCAL ROLE authenticated;
SELECT throws_ok($$SELECT * FROM public.claim_media_upload_intents_for_reclaim('{}'::uuid[])$$, '42501', 'permission denied for function claim_media_upload_intents_for_reclaim', 'actual authenticated execution is denied');
RESET ROLE;
SET LOCAL ROLE anon;
SELECT throws_ok($$SELECT * FROM public.claim_media_upload_intents_for_reclaim('{}'::uuid[])$$, '42501', 'permission denied for function claim_media_upload_intents_for_reclaim', 'actual anonymous execution is denied');
RESET ROLE;
SET LOCAL ROLE service_role;
SELECT is((SELECT count(*) FROM public.claim_media_upload_intents_for_reclaim('{}'::uuid[])), 0::bigint, 'an empty batch changes nothing');
SELECT throws_ok($$SELECT * FROM public.claim_media_upload_intents_for_reclaim(NULL)$$, '22023', 'At most 500 exact upload intents are required', 'null batch is rejected');
SELECT throws_ok($$SELECT * FROM public.claim_media_upload_intents_for_reclaim(ARRAY[NULL]::uuid[])$$, '22023', 'At most 500 exact upload intents are required', 'null identities are rejected');
SELECT throws_ok($$SELECT * FROM public.claim_media_upload_intents_for_reclaim(array_fill('84d86baa-c9e9-4932-b533-f3e04216183c'::uuid, ARRAY[501]))$$, '22023', 'At most 500 exact upload intents are required', 'oversized batch is rejected');
RESET ROLE;
SELECT * FROM finish();
ROLLBACK;
