const {
  createRunOncePlugin,
  withAppBuildGradle,
  withGradleProperties,
  withSettingsGradle,
} = require('expo/config-plugins');

const PLUGIN_NAME = 'withAndroidReleaseSafety';
const PLUGIN_VERSION = '3.0.0';
const MATERIAL_COMPONENTS_VERSION = '1.14.0';
// R8 is off, deliberately. expo-modules-core converts every JS options object
// into a Kotlin record by reflection, and R8's optimization passes strip the
// metadata that depends on. With minification on, `expo-secure-store` rejected
// every getValueWithKeyAsync ("The 2nd argument cannot be cast to type
// SecureStoreOptions") which put the app in a permanent sign-out loop, and
// `expo-image` could not set `source` or `contentPosition`, so no image ever
// mounted. Both shipped in 0.1.2 (build 62) and made the alpha unusable.
//
// Turning this back on requires -keep rules for expo.modules.** and Kotlin
// metadata, verified on a device — not just a green build. A missing rule fails
// exactly like this: silently, at runtime, in whichever module is unlucky.
const RELEASE_PROPERTIES = {
  'android.enableMinifyInReleaseBuilds': 'false',
  'android.enableShrinkResourcesInReleaseBuilds': 'false',
  'org.gradle.jvmargs': '-Xmx3072m -XX:MaxMetaspaceSize=1536m',
};

function withAndroidReleaseSafety(config) {
  const configWithReleaseProperties = withGradleProperties(config, (nextConfig) => {
    nextConfig.modResults = setReleaseSafetyProperties(nextConfig.modResults);
    return nextConfig;
  });

  const configWithAppBuildGradle = withAppBuildGradle(configWithReleaseProperties, (nextConfig) => {
    nextConfig.modResults.contents = setMaterialComponentsVersion(
      setReleaseProguardSafety(nextConfig.modResults.contents)
    );
    return nextConfig;
  });

  return withSettingsGradle(configWithAppBuildGradle, (nextConfig) => {
    nextConfig.modResults.contents = setReactNativeBuildFromSource(nextConfig.modResults.contents);
    return nextConfig;
  });
}

function setReleaseSafetyProperties(properties) {
  const nextProperties = [...properties];

  for (const [key, value] of Object.entries(RELEASE_PROPERTIES)) {
    const existing = nextProperties.find((entry) => entry.type === 'property' && entry.key === key);
    if (existing && existing.type === 'property') {
      existing.value = value;
      continue;
    }
    nextProperties.push({ type: 'property', key, value });
  }

  return nextProperties;
}

/**
 * Pin the release build to the plain ProGuard default. `proguard-android-optimize.txt`
 * adds the optimization passes that break expo-modules-core's reflection, so it
 * is reverted here even while minification is off — the two were turned on
 * together and must not drift back apart independently.
 */
function setReleaseProguardSafety(buildGradle) {
  const safeDefault = 'getDefaultProguardFile("proguard-android.txt")';
  if (/getDefaultProguardFile\((["'])proguard-android\.txt\1\)/.test(buildGradle)) {
    return buildGradle;
  }

  const optimizedDefault = /getDefaultProguardFile\((["'])proguard-android-optimize\.txt\1\)/g;
  if (!optimizedDefault.test(buildGradle)) {
    throw new Error('Could not locate the Android release ProGuard default configuration.');
  }

  return buildGradle.replace(optimizedDefault, safeDefault);
}

function setMaterialComponentsVersion(buildGradle) {
  const dependency = `implementation("com.google.android.material:material:${MATERIAL_COMPONENTS_VERSION}")`;
  if (buildGradle.includes(dependency)) {
    return buildGradle;
  }

  const dependenciesBlock = /dependencies\s*\{/;
  if (!dependenciesBlock.test(buildGradle)) {
    throw new Error('Could not locate the Android dependencies block.');
  }

  return buildGradle.replace(dependenciesBlock, (match) => `${match}\n    ${dependency}`);
}

function setReactNativeBuildFromSource(settingsGradle) {
  const marker = '// @generated by withAndroidReleaseSafety - React Native source build';
  if (settingsGradle.includes(marker)) {
    return settingsGradle;
  }

  return `${settingsGradle.trimEnd()}

${marker}
includeBuild('../node_modules/react-native') {
  dependencySubstitution {
    substitute(module('com.facebook.react:react-android')).using(project(':packages:react-native:ReactAndroid'))
    substitute(module('com.facebook.react:react-native')).using(project(':packages:react-native:ReactAndroid'))
  }
}
`;
}

const plugin = createRunOncePlugin(
  withAndroidReleaseSafety,
  PLUGIN_NAME,
  PLUGIN_VERSION
);

module.exports = plugin;
module.exports.setMaterialComponentsVersion = setMaterialComponentsVersion;
module.exports.setReactNativeBuildFromSource = setReactNativeBuildFromSource;
module.exports.setReleaseProguardSafety = setReleaseProguardSafety;
module.exports.setReleaseSafetyProperties = setReleaseSafetyProperties;
module.exports.withAndroidReleaseSafety = withAndroidReleaseSafety;
