const {
  createRunOncePlugin,
  withPodfile,
  withSettingsGradle,
  withXcodeProject,
} = require('expo/config-plugins');

const PLUGIN_NAME = 'withBuildProfileAutolinking';
const PLUGIN_VERSION = '1.0.0';
const BUILD_PROFILE_ENV = 'MAGICBOOKLET_INCLUDE_DEV_CLIENT';
// expo-manifests used to belong here because only the dev client pulled it in.
// expo-updates depends on it too, so excluding it breaks the pod graph:
// `pod install` fails with "Unable to find a specification for EXManifests
// depended upon by EXUpdates". That only happens when INCLUDE_DEV_CLIENT is
// false, so development builds stay green and preview/production builds fail.
// See the autolinking test that pins this.
const DEVELOPMENT_ONLY_NATIVE_MODULES = [
  'expo-dev-client',
  'expo-dev-launcher',
  'expo-dev-menu',
  'expo-dev-menu-interface',
];
const ANDROID_BLOCK_BEGIN = '// @generated by withBuildProfileAutolinking - begin';
const ANDROID_BLOCK_END = '// @generated by withBuildProfileAutolinking - end';
const IOS_BLOCK_BEGIN = '# @generated by withBuildProfileAutolinking - begin';
const IOS_BLOCK_END = '# @generated by withBuildProfileAutolinking - end';
const IOS_BUNDLE_PHASE_NAME = 'Bundle React Native code and images';
const IOS_UNSAFE_BUNDLE_SCRIPT =
  '`"$NODE_BINARY" --print "require(\'path\').dirname(require.resolve(\'react-native/package.json\')) + \'/scripts/react-native-xcode.sh\'"`';
const IOS_PATH_SAFE_BUNDLE_SCRIPT = [
  'REACT_NATIVE_XCODE_SCRIPT="$("$NODE_BINARY" --print "require(\'path\').dirname(require.resolve(\'react-native/package.json\')) + \'/scripts/react-native-xcode.sh\'")"',
  '"$REACT_NATIVE_XCODE_SCRIPT"',
].join('\n');

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function stripAndroidBlock(contents) {
  const blockPattern = new RegExp(
    `${escapeRegExp(ANDROID_BLOCK_BEGIN)}[\\s\\S]*?${escapeRegExp(ANDROID_BLOCK_END)}\\n?`,
    'g'
  );
  return contents.replace(blockPattern, '');
}

function stripIosBlock(contents) {
  const blockPattern = new RegExp(
    `${escapeRegExp(IOS_BLOCK_BEGIN)}[\\s\\S]*?${escapeRegExp(IOS_BLOCK_END)}`,
    'g'
  );
  return contents.replace(blockPattern, 'use_expo_modules!');
}

function androidExclusionBlock(indent) {
  const moduleLines = DEVELOPMENT_ONLY_NATIVE_MODULES
    .map((moduleName) => `${indent}    '${moduleName}',`)
    .join('\n');

  return [
    `${indent}${ANDROID_BLOCK_BEGIN}`,
    `${indent}if (System.getenv('${BUILD_PROFILE_ENV}') == 'false') {`,
    `${indent}  expoAutolinking.exclude = [`,
    moduleLines,
    `${indent}  ]`,
    `${indent}}`,
    `${indent}${ANDROID_BLOCK_END}`,
  ].join('\n');
}

function iosExclusionBlock(indent) {
  const moduleLines = DEVELOPMENT_ONLY_NATIVE_MODULES
    .map((moduleName) => `${indent}  '${moduleName}',`)
    .join('\n');

  return [
    `${indent}${IOS_BLOCK_BEGIN}`,
    `${indent}development_only_native_modules = ENV['${BUILD_PROFILE_ENV}'] == 'false' ? [`,
    moduleLines,
    `${indent}] : []`,
    `${indent}use_expo_modules!(`,
    `${indent}  :exclude => development_only_native_modules`,
    `${indent})`,
    `${indent}${IOS_BLOCK_END}`,
  ].join('\n');
}

function setAndroidBuildProfileAutolinking(contents) {
  const withoutGeneratedBlock = stripAndroidBlock(contents);
  const anchorPattern = /^(\s*)expoAutolinking\.useExpoModules\(\)\s*$/m;

  if (!anchorPattern.test(withoutGeneratedBlock)) {
    throw new Error(`${PLUGIN_NAME} could not find expoAutolinking.useExpoModules()`);
  }

  return withoutGeneratedBlock.replace(
    anchorPattern,
    (anchor, indent) => `${androidExclusionBlock(indent)}\n${anchor}`
  );
}

function setIosBuildProfileAutolinking(contents) {
  const withoutGeneratedBlock = stripIosBlock(contents);
  const anchorPattern = /^(\s*)use_expo_modules!\s*$/m;

  if (!anchorPattern.test(withoutGeneratedBlock)) {
    throw new Error(`${PLUGIN_NAME} could not find use_expo_modules!`);
  }

  return withoutGeneratedBlock.replace(
    anchorPattern,
    (_anchor, indent) => iosExclusionBlock(indent)
  );
}

function parseXcodeString(value) {
  if (typeof value !== 'string') {
    return null;
  }

  try {
    return JSON.parse(value);
  } catch {
    return value;
  }
}

function setPathSafeIosBundleScript(project) {
  const phases = project.hash?.project?.objects?.PBXShellScriptBuildPhase;
  if (!phases) {
    throw new Error(`${PLUGIN_NAME} could not find iOS shell script build phases`);
  }

  const bundlePhase = Object.values(phases).find(
    (phase) =>
      phase &&
      typeof phase === 'object' &&
      parseXcodeString(phase.name) === IOS_BUNDLE_PHASE_NAME
  );

  if (!bundlePhase) {
    throw new Error(`${PLUGIN_NAME} could not find the iOS JavaScript bundle phase`);
  }

  const script = parseXcodeString(bundlePhase.shellScript);
  if (typeof script !== 'string') {
    throw new Error(`${PLUGIN_NAME} could not read the iOS JavaScript bundle script`);
  }

  if (script.includes(IOS_PATH_SAFE_BUNDLE_SCRIPT)) {
    return project;
  }

  if (!script.includes(IOS_UNSAFE_BUNDLE_SCRIPT)) {
    throw new Error(`${PLUGIN_NAME} could not find the iOS bundle script invocation`);
  }

  bundlePhase.shellScript = JSON.stringify(
    script.replace(IOS_UNSAFE_BUNDLE_SCRIPT, IOS_PATH_SAFE_BUNDLE_SCRIPT)
  );
  return project;
}

function withBuildProfileAutolinking(config) {
  config = withSettingsGradle(config, (nextConfig) => {
    if (nextConfig.modResults.language !== 'groovy') {
      throw new Error(`${PLUGIN_NAME} requires a Groovy settings.gradle file`);
    }
    nextConfig.modResults.contents = setAndroidBuildProfileAutolinking(
      nextConfig.modResults.contents
    );
    return nextConfig;
  });

  config = withPodfile(config, (nextConfig) => {
    nextConfig.modResults.contents = setIosBuildProfileAutolinking(
      nextConfig.modResults.contents
    );
    return nextConfig;
  });

  config = withXcodeProject(config, (nextConfig) => {
    nextConfig.modResults = setPathSafeIosBundleScript(nextConfig.modResults);
    return nextConfig;
  });

  return config;
}

const plugin = createRunOncePlugin(
  withBuildProfileAutolinking,
  PLUGIN_NAME,
  PLUGIN_VERSION
);

module.exports = plugin;
module.exports.DEVELOPMENT_ONLY_NATIVE_MODULES = DEVELOPMENT_ONLY_NATIVE_MODULES;
module.exports.setAndroidBuildProfileAutolinking = setAndroidBuildProfileAutolinking;
module.exports.setIosBuildProfileAutolinking = setIosBuildProfileAutolinking;
module.exports.setPathSafeIosBundleScript = setPathSafeIosBundleScript;
module.exports.withBuildProfileAutolinking = withBuildProfileAutolinking;
