const {
  createRunOncePlugin,
  withAppBuildGradle,
  withGradleProperties,
  withSettingsGradle,
} = require('expo/config-plugins');

const PLUGIN_NAME = 'withAndroidReleaseSafety';
const PLUGIN_VERSION = '2.0.0';
const MATERIAL_COMPONENTS_VERSION = '1.14.0';
const RELEASE_PROPERTIES = {
  'android.enableMinifyInReleaseBuilds': 'true',
  'android.enableShrinkResourcesInReleaseBuilds': 'true',
  'android.r8.optimizedResourceShrinking': 'true',
  'org.gradle.jvmargs': '-Xmx3072m -XX:MaxMetaspaceSize=1536m',
};

function withAndroidReleaseSafety(config) {
  const configWithReleaseProperties = withGradleProperties(config, (nextConfig) => {
    nextConfig.modResults = setReleaseSafetyProperties(nextConfig.modResults);
    return nextConfig;
  });

  const configWithAppBuildGradle = withAppBuildGradle(configWithReleaseProperties, (nextConfig) => {
    nextConfig.modResults.contents = setMaterialComponentsVersion(
      setReleaseProguardOptimization(nextConfig.modResults.contents)
    );
    return nextConfig;
  });

  return withSettingsGradle(configWithAppBuildGradle, (nextConfig) => {
    nextConfig.modResults.contents = setReactNativeBuildFromSource(nextConfig.modResults.contents);
    return nextConfig;
  });
}

function setReleaseSafetyProperties(properties) {
  const nextProperties = [...properties];

  for (const [key, value] of Object.entries(RELEASE_PROPERTIES)) {
    const existing = nextProperties.find((entry) => entry.type === 'property' && entry.key === key);
    if (existing && existing.type === 'property') {
      existing.value = value;
      continue;
    }
    nextProperties.push({ type: 'property', key, value });
  }

  return nextProperties;
}

function setReleaseProguardOptimization(buildGradle) {
  const optimizedDefault = 'getDefaultProguardFile("proguard-android-optimize.txt")';
  if (/getDefaultProguardFile\((["'])proguard-android-optimize\.txt\1\)/.test(buildGradle)) {
    return buildGradle;
  }

  const unoptimizedDefault = /getDefaultProguardFile\((["'])proguard-android\.txt\1\)/g;
  if (!unoptimizedDefault.test(buildGradle)) {
    throw new Error('Could not locate the Android release ProGuard default configuration.');
  }

  return buildGradle.replace(unoptimizedDefault, optimizedDefault);
}

function setMaterialComponentsVersion(buildGradle) {
  const dependency = `implementation("com.google.android.material:material:${MATERIAL_COMPONENTS_VERSION}")`;
  if (buildGradle.includes(dependency)) {
    return buildGradle;
  }

  const dependenciesBlock = /dependencies\s*\{/;
  if (!dependenciesBlock.test(buildGradle)) {
    throw new Error('Could not locate the Android dependencies block.');
  }

  return buildGradle.replace(dependenciesBlock, (match) => `${match}\n    ${dependency}`);
}

function setReactNativeBuildFromSource(settingsGradle) {
  const marker = '// @generated by withAndroidReleaseSafety - React Native source build';
  if (settingsGradle.includes(marker)) {
    return settingsGradle;
  }

  return `${settingsGradle.trimEnd()}

${marker}
includeBuild('../node_modules/react-native') {
  dependencySubstitution {
    substitute(module('com.facebook.react:react-android')).using(project(':packages:react-native:ReactAndroid'))
    substitute(module('com.facebook.react:react-native')).using(project(':packages:react-native:ReactAndroid'))
  }
}
`;
}

const plugin = createRunOncePlugin(
  withAndroidReleaseSafety,
  PLUGIN_NAME,
  PLUGIN_VERSION
);

module.exports = plugin;
module.exports.setMaterialComponentsVersion = setMaterialComponentsVersion;
module.exports.setReactNativeBuildFromSource = setReactNativeBuildFromSource;
module.exports.setReleaseProguardOptimization = setReleaseProguardOptimization;
module.exports.setReleaseSafetyProperties = setReleaseSafetyProperties;
module.exports.withAndroidReleaseSafety = withAndroidReleaseSafety;
