CREATE TABLE IF NOT EXISTS public.post_resource_bundles (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  post_id uuid UNIQUE NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  owner_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  legacy_asset_id uuid UNIQUE REFERENCES public.marketplace_assets(id) ON DELETE SET NULL,
  access_mode text NOT NULL CHECK (access_mode IN ('free', 'paid')),
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
  title text NOT NULL,
  summary text NOT NULL DEFAULT '',
  preview_text text NOT NULL DEFAULT '',
  prompt_text text,
  notes_markdown text,
  workflow_share_url text,
  workflow_snapshot jsonb,
  attachments jsonb NOT NULL DEFAULT '[]'::jsonb,
  allow_remix boolean NOT NULL DEFAULT false,
  price_usd_cents integer NOT NULL DEFAULT 0 CHECK (price_usd_cents = 0 OR price_usd_cents >= 100),
  sales_count integer NOT NULL DEFAULT 0,
  earnings_usd_cents integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT post_resource_bundles_access_mode_price_check CHECK (
    (access_mode = 'free' AND price_usd_cents = 0)
    OR (access_mode = 'paid' AND price_usd_cents >= 100)
  ),
  CONSTRAINT post_resource_bundles_attachments_array_check CHECK (jsonb_typeof(attachments) = 'array')
);

CREATE TABLE IF NOT EXISTS public.post_resource_bundle_orders (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  bundle_id uuid NOT NULL REFERENCES public.post_resource_bundles(id) ON DELETE CASCADE,
  buyer_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  legacy_order_id uuid UNIQUE REFERENCES public.marketplace_orders(id) ON DELETE SET NULL,
  razorpay_order_id text UNIQUE NOT NULL,
  razorpay_payment_id text,
  amount_subunits integer NOT NULL,
  currency text NOT NULL CHECK (currency IN ('INR', 'USD')),
  status text NOT NULL DEFAULT 'created' CHECK (status IN ('created', 'paid', 'failed')),
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.post_resource_bundle_purchases (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  bundle_id uuid NOT NULL REFERENCES public.post_resource_bundles(id) ON DELETE CASCADE,
  buyer_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  order_id uuid NOT NULL REFERENCES public.post_resource_bundle_orders(id) ON DELETE CASCADE,
  legacy_purchase_id uuid UNIQUE REFERENCES public.marketplace_purchases(id) ON DELETE SET NULL,
  price_usd_cents integer NOT NULL,
  amount_subunits integer NOT NULL,
  currency text NOT NULL CHECK (currency IN ('INR', 'USD')),
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  UNIQUE (bundle_id, buyer_user_id)
);

CREATE TABLE IF NOT EXISTS public.post_resource_bundle_migration_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_asset_id uuid,
  post_id uuid,
  outcome text NOT NULL CHECK (outcome IN ('migrated', 'skipped_no_post', 'skipped_not_public', 'skipped_invalid')),
  note text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS post_resource_bundles_status_created_idx
  ON public.post_resource_bundles (status, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS post_resource_bundles_access_mode_created_idx
  ON public.post_resource_bundles (access_mode, created_at DESC, id DESC)
  WHERE status = 'published';

CREATE INDEX IF NOT EXISTS post_resource_bundles_sales_idx
  ON public.post_resource_bundles (sales_count DESC, created_at DESC, id DESC)
  WHERE status = 'published';

CREATE INDEX IF NOT EXISTS post_resource_bundle_orders_buyer_created_idx
  ON public.post_resource_bundle_orders (buyer_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS post_resource_bundle_orders_bundle_created_idx
  ON public.post_resource_bundle_orders (bundle_id, created_at DESC);

CREATE INDEX IF NOT EXISTS post_resource_bundle_purchases_buyer_created_idx
  ON public.post_resource_bundle_purchases (buyer_user_id, created_at DESC);

ALTER TABLE public.post_resource_bundles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_resource_bundle_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_resource_bundle_purchases ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Post resource bundles are viewable by owner or published" ON public.post_resource_bundles;
CREATE POLICY "Post resource bundles are viewable by owner or published"
  ON public.post_resource_bundles FOR SELECT TO public
  USING (status = 'published' OR auth.uid() = owner_user_id);

DROP POLICY IF EXISTS "Users can insert their own post resource bundles" ON public.post_resource_bundles;
CREATE POLICY "Users can insert their own post resource bundles"
  ON public.post_resource_bundles FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = owner_user_id);

DROP POLICY IF EXISTS "Users can update their own post resource bundles" ON public.post_resource_bundles;
CREATE POLICY "Users can update their own post resource bundles"
  ON public.post_resource_bundles FOR UPDATE TO authenticated
  USING (auth.uid() = owner_user_id)
  WITH CHECK (auth.uid() = owner_user_id);

DROP POLICY IF EXISTS "Users can delete their own post resource bundles" ON public.post_resource_bundles;
CREATE POLICY "Users can delete their own post resource bundles"
  ON public.post_resource_bundles FOR DELETE TO authenticated
  USING (auth.uid() = owner_user_id);

DROP POLICY IF EXISTS "Buyers can view their own post resource bundle orders" ON public.post_resource_bundle_orders;
CREATE POLICY "Buyers can view their own post resource bundle orders"
  ON public.post_resource_bundle_orders FOR SELECT TO authenticated
  USING (auth.uid() = buyer_user_id);

DROP POLICY IF EXISTS "Buyers can view their own post resource bundle purchases" ON public.post_resource_bundle_purchases;
CREATE POLICY "Buyers can view their own post resource bundle purchases"
  ON public.post_resource_bundle_purchases FOR SELECT TO authenticated
  USING (auth.uid() = buyer_user_id);

CREATE OR REPLACE FUNCTION public.validate_post_resource_bundle_write()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_post public.posts%ROWTYPE;
BEGIN
  SELECT *
  INTO v_post
  FROM public.posts
  WHERE id = NEW.post_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Attached post not found';
  END IF;

  IF NEW.owner_user_id <> v_post.user_id THEN
    RAISE EXCEPTION 'Bundle owner must match post owner';
  END IF;

  IF NEW.status = 'published' AND v_post.visibility IS DISTINCT FROM 'public' THEN
    RAISE EXCEPTION 'Only public posts can publish resource bundles';
  END IF;

  IF NEW.access_mode = 'free' AND NEW.price_usd_cents <> 0 THEN
    RAISE EXCEPTION 'Free bundles must have a zero price';
  END IF;

  IF NEW.access_mode = 'paid' AND NEW.price_usd_cents < 100 THEN
    RAISE EXCEPTION 'Paid bundles must cost at least 100 cents';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS post_resource_bundles_validate_write ON public.post_resource_bundles;
CREATE TRIGGER post_resource_bundles_validate_write
BEFORE INSERT OR UPDATE ON public.post_resource_bundles
FOR EACH ROW
EXECUTE FUNCTION public.validate_post_resource_bundle_write();

DROP TRIGGER IF EXISTS post_resource_bundles_set_updated_at ON public.post_resource_bundles;
CREATE TRIGGER post_resource_bundles_set_updated_at
BEFORE UPDATE ON public.post_resource_bundles
FOR EACH ROW
EXECUTE FUNCTION public.touch_updated_at_column();

DROP TRIGGER IF EXISTS post_resource_bundle_orders_set_updated_at ON public.post_resource_bundle_orders;
CREATE TRIGGER post_resource_bundle_orders_set_updated_at
BEFORE UPDATE ON public.post_resource_bundle_orders
FOR EACH ROW
EXECUTE FUNCTION public.touch_updated_at_column();

CREATE OR REPLACE FUNCTION public.complete_post_resource_bundle_purchase(
  p_razorpay_order_id text,
  p_razorpay_payment_id text
)
RETURNS boolean AS $$
DECLARE
  v_order public.post_resource_bundle_orders%ROWTYPE;
  v_bundle public.post_resource_bundles%ROWTYPE;
  v_purchase_id uuid;
BEGIN
  SELECT *
  INTO v_order
  FROM public.post_resource_bundle_orders
  WHERE razorpay_order_id = p_razorpay_order_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN false;
  END IF;

  IF v_order.status = 'paid' THEN
    RETURN false;
  END IF;

  SELECT *
  INTO v_bundle
  FROM public.post_resource_bundles
  WHERE id = v_order.bundle_id;

  IF NOT FOUND THEN
    RETURN false;
  END IF;

  UPDATE public.post_resource_bundle_orders
  SET status = 'paid',
      razorpay_payment_id = p_razorpay_payment_id,
      updated_at = timezone('utc'::text, now())
  WHERE id = v_order.id;

  INSERT INTO public.post_resource_bundle_purchases (
    bundle_id,
    buyer_user_id,
    order_id,
    price_usd_cents,
    amount_subunits,
    currency
  )
  VALUES (
    v_order.bundle_id,
    v_order.buyer_user_id,
    v_order.id,
    v_bundle.price_usd_cents,
    v_order.amount_subunits,
    v_order.currency
  )
  ON CONFLICT (bundle_id, buyer_user_id) DO NOTHING
  RETURNING id INTO v_purchase_id;

  IF v_purchase_id IS NULL THEN
    RETURN false;
  END IF;

  UPDATE public.post_resource_bundles
  SET sales_count = sales_count + 1,
      earnings_usd_cents = earnings_usd_cents + v_bundle.price_usd_cents,
      updated_at = timezone('utc'::text, now())
  WHERE id = v_order.bundle_id;

  RETURN true;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.complete_post_resource_bundle_purchase(text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.complete_post_resource_bundle_purchase(text, text) FROM anon;
REVOKE ALL ON FUNCTION public.complete_post_resource_bundle_purchase(text, text) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.complete_post_resource_bundle_purchase(text, text) TO service_role;

INSERT INTO public.post_resource_bundles (
  post_id,
  owner_user_id,
  legacy_asset_id,
  access_mode,
  status,
  title,
  summary,
  preview_text,
  prompt_text,
  notes_markdown,
  workflow_snapshot,
  attachments,
  allow_remix,
  price_usd_cents,
  sales_count,
  earnings_usd_cents,
  created_at,
  updated_at
)
SELECT
  assets.post_id,
  assets.seller_user_id,
  assets.id,
  CASE
    WHEN assets.price_usd_cents = 0 THEN 'free'
    ELSE 'paid'
  END,
  CASE
    WHEN assets.status = 'active' AND posts.visibility = 'public' THEN 'published'
    ELSE 'draft'
  END,
  COALESCE(NULLIF(assets.title, ''), COALESCE(posts.title, 'Attached resources')),
  assets.description,
  assets.preview,
  content.prompt_pack,
  content.guide_markdown,
  content.workflow_graph,
  '[]'::jsonb,
  false,
  assets.price_usd_cents,
  assets.sales_count,
  assets.earnings_usd_cents,
  assets.created_at,
  assets.updated_at
FROM public.marketplace_assets assets
JOIN public.posts
  ON posts.id = assets.post_id
LEFT JOIN public.marketplace_asset_content content
  ON content.asset_id = assets.id
WHERE assets.post_id IS NOT NULL
  AND assets.status <> 'deleted'
ON CONFLICT (post_id) DO UPDATE
SET
  legacy_asset_id = EXCLUDED.legacy_asset_id,
  access_mode = EXCLUDED.access_mode,
  status = EXCLUDED.status,
  title = EXCLUDED.title,
  summary = EXCLUDED.summary,
  preview_text = EXCLUDED.preview_text,
  prompt_text = EXCLUDED.prompt_text,
  notes_markdown = EXCLUDED.notes_markdown,
  workflow_snapshot = EXCLUDED.workflow_snapshot,
  price_usd_cents = EXCLUDED.price_usd_cents,
  sales_count = EXCLUDED.sales_count,
  earnings_usd_cents = EXCLUDED.earnings_usd_cents,
  updated_at = timezone('utc'::text, now());

INSERT INTO public.post_resource_bundle_orders (
  bundle_id,
  buyer_user_id,
  legacy_order_id,
  razorpay_order_id,
  razorpay_payment_id,
  amount_subunits,
  currency,
  status,
  created_at,
  updated_at
)
SELECT
  bundles.id,
  orders.buyer_user_id,
  orders.id,
  orders.razorpay_order_id,
  orders.razorpay_payment_id,
  orders.amount_subunits,
  orders.currency,
  orders.status,
  orders.created_at,
  orders.updated_at
FROM public.marketplace_orders orders
JOIN public.post_resource_bundles bundles
  ON bundles.legacy_asset_id = orders.asset_id
ON CONFLICT (legacy_order_id) DO NOTHING;

INSERT INTO public.post_resource_bundle_purchases (
  bundle_id,
  buyer_user_id,
  order_id,
  legacy_purchase_id,
  price_usd_cents,
  amount_subunits,
  currency,
  created_at
)
SELECT
  bundles.id,
  purchases.buyer_user_id,
  bundle_orders.id,
  purchases.id,
  purchases.price_usd_cents,
  purchases.amount_subunits,
  purchases.currency,
  purchases.created_at
FROM public.marketplace_purchases purchases
JOIN public.post_resource_bundles bundles
  ON bundles.legacy_asset_id = purchases.asset_id
JOIN public.post_resource_bundle_orders bundle_orders
  ON bundle_orders.legacy_order_id = purchases.order_id
ON CONFLICT (legacy_purchase_id) DO NOTHING;

INSERT INTO public.post_resource_bundle_migration_audit (legacy_asset_id, post_id, outcome, note)
SELECT assets.id, assets.post_id, 'migrated', 'Legacy marketplace asset was migrated into a post resource bundle.'
FROM public.marketplace_assets assets
WHERE assets.post_id IS NOT NULL
  AND assets.status <> 'deleted'
ON CONFLICT DO NOTHING;

INSERT INTO public.post_resource_bundle_migration_audit (legacy_asset_id, post_id, outcome, note)
SELECT assets.id, assets.post_id, 'skipped_no_post', 'Legacy marketplace asset has no attached post and stays out of the public bundle system.'
FROM public.marketplace_assets assets
WHERE assets.post_id IS NULL
  AND assets.status <> 'deleted'
ON CONFLICT DO NOTHING;
