-- Resource package economics use whole tokens for pricing (100 tokens = USD 1)
-- and hundredths of a token for settlement. The finer settlement unit keeps an
-- exact 85/15 split even for the 10-token minimum price.

ALTER TABLE public.post_resource_bundles
  ADD COLUMN IF NOT EXISTS gross_sales_tokens bigint NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS creator_earnings_token_subunits bigint NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS platform_fee_token_subunits bigint NOT NULL DEFAULT 0;

COMMENT ON COLUMN public.post_resource_bundles.price_usd_cents IS
  'Resource package price in whole tokens. At the fixed 100-token/USD rate, one token is also one USD cent.';
COMMENT ON COLUMN public.post_resource_bundles.earnings_usd_cents IS
  'Legacy creator earnings projection in whole USD cents, rounded down from exact token subunits.';
COMMENT ON COLUMN public.post_resource_bundles.creator_earnings_token_subunits IS
  'Exact creator proceeds where 100 subunits equal one token; creator share is 85 percent.';
COMMENT ON COLUMN public.post_resource_bundles.platform_fee_token_subunits IS
  'Exact platform proceeds where 100 subunits equal one token; platform share is 15 percent.';

-- Native clients unlock post packages with their credit balance. Keep existing
-- pending store intents settleable for backward compatibility, but reject all
-- newly-created direct-IAP intents for this entitlement type.
UPDATE public.mobile_store_products
SET active = false,
    updated_at = timezone('utc'::text, now())
WHERE entitlement_type = 'post_resource_unlock'
  AND active = true;

CREATE OR REPLACE FUNCTION public.enforce_mobile_post_resources_credit_only()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NEW.entitlement_type = 'post_resource_unlock' THEN
    RAISE EXCEPTION 'Post resource packages are credit-only on mobile';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS mobile_post_resources_credit_only
  ON public.mobile_purchase_intents;
CREATE TRIGGER mobile_post_resources_credit_only
BEFORE INSERT ON public.mobile_purchase_intents
FOR EACH ROW
EXECUTE FUNCTION public.enforce_mobile_post_resources_credit_only();

REVOKE ALL ON FUNCTION public.enforce_mobile_post_resources_credit_only()
  FROM PUBLIC, anon, authenticated;

CREATE TABLE IF NOT EXISTS public.creator_resource_wallets (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  available_token_subunits bigint NOT NULL DEFAULT 0,
  lifetime_earned_token_subunits bigint NOT NULL DEFAULT 0 CHECK (lifetime_earned_token_subunits >= 0),
  lifetime_refunded_token_subunits bigint NOT NULL DEFAULT 0 CHECK (lifetime_refunded_token_subunits >= 0),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.creator_resource_wallet_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key text UNIQUE NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  bundle_id uuid REFERENCES public.post_resource_bundles(id) ON DELETE SET NULL,
  purchase_id uuid,
  order_id uuid,
  entry_kind text NOT NULL CHECK (entry_kind IN ('sale', 'refund', 'legacy_sale')),
  gross_token_units integer NOT NULL CHECK (gross_token_units >= 0),
  creator_amount_token_subunits bigint NOT NULL,
  platform_fee_token_subunits bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT creator_resource_wallet_entry_split_check CHECK (
    creator_amount_token_subunits + platform_fee_token_subunits
      = CASE
          WHEN entry_kind = 'refund' THEN -(gross_token_units::bigint * 100)
          ELSE gross_token_units::bigint * 100
        END
  )
);

CREATE INDEX IF NOT EXISTS creator_resource_wallet_entries_user_created_idx
  ON public.creator_resource_wallet_entries (user_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS creator_resource_wallet_entries_bundle_idx
  ON public.creator_resource_wallet_entries (bundle_id, id DESC);
CREATE INDEX IF NOT EXISTS creator_resource_wallet_entries_purchase_idx
  ON public.creator_resource_wallet_entries (purchase_id)
  WHERE purchase_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS creator_resource_wallet_entries_order_idx
  ON public.creator_resource_wallet_entries (order_id, id DESC)
  WHERE order_id IS NOT NULL;

ALTER TABLE public.creator_resource_wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.creator_resource_wallet_entries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Creators can view their resource wallet"
  ON public.creator_resource_wallets;
CREATE POLICY "Creators can view their resource wallet"
  ON public.creator_resource_wallets FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Creators can view their resource wallet entries"
  ON public.creator_resource_wallet_entries;
CREATE POLICY "Creators can view their resource wallet entries"
  ON public.creator_resource_wallet_entries FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

REVOKE ALL ON public.creator_resource_wallets FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.creator_resource_wallet_entries FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.creator_resource_wallets TO authenticated;
GRANT SELECT ON public.creator_resource_wallet_entries TO authenticated;

-- Backfill each retained purchase. The purchase price is the authoritative
-- token amount; payment-provider subunits may instead be INR or another cash
-- currency and must not be used for the creator split.
INSERT INTO public.creator_resource_wallet_entries (
  event_key,
  user_id,
  bundle_id,
  purchase_id,
  order_id,
  entry_kind,
  gross_token_units,
  creator_amount_token_subunits,
  platform_fee_token_subunits,
  created_at
)
SELECT
  'purchase:' || purchases.id::text,
  bundles.owner_user_id,
  bundles.id,
  purchases.id,
  purchases.order_id,
  'sale',
  purchases.price_usd_cents,
  purchases.price_usd_cents::bigint * 85,
  purchases.price_usd_cents::bigint * 15,
  purchases.created_at
FROM public.post_resource_bundle_purchases AS purchases
JOIN public.post_resource_bundles AS bundles ON bundles.id = purchases.bundle_id
WHERE purchases.price_usd_cents > 0
ON CONFLICT (event_key) DO NOTHING;

-- Preserve pre-ledger aggregate sales that no longer have individual retained
-- purchase rows (for example, legacy imports). This credits only the positive
-- gap and never double-counts purchases backfilled above.
WITH retained_sales AS (
  SELECT
    bundles.id AS bundle_id,
    bundles.owner_user_id,
    bundles.created_at,
    greatest(
      0,
      bundles.earnings_usd_cents
        - coalesce(sum(purchases.price_usd_cents), 0)
    )::integer AS legacy_gross_tokens
  FROM public.post_resource_bundles AS bundles
  LEFT JOIN public.post_resource_bundle_purchases AS purchases
    ON purchases.bundle_id = bundles.id
  GROUP BY bundles.id, bundles.owner_user_id, bundles.created_at, bundles.earnings_usd_cents
)
INSERT INTO public.creator_resource_wallet_entries (
  event_key,
  user_id,
  bundle_id,
  purchase_id,
  order_id,
  entry_kind,
  gross_token_units,
  creator_amount_token_subunits,
  platform_fee_token_subunits,
  created_at
)
SELECT
  'legacy-bundle:' || bundle_id::text,
  owner_user_id,
  bundle_id,
  NULL,
  NULL,
  'legacy_sale',
  legacy_gross_tokens,
  legacy_gross_tokens::bigint * 85,
  legacy_gross_tokens::bigint * 15,
  created_at
FROM retained_sales
WHERE legacy_gross_tokens > 0
ON CONFLICT (event_key) DO NOTHING;

INSERT INTO public.creator_resource_wallets (
  user_id,
  available_token_subunits,
  lifetime_earned_token_subunits,
  lifetime_refunded_token_subunits,
  updated_at
)
SELECT
  entries.user_id,
  sum(entries.creator_amount_token_subunits),
  sum(greatest(entries.creator_amount_token_subunits, 0)),
  sum(greatest(-entries.creator_amount_token_subunits, 0)),
  timezone('utc'::text, now())
FROM public.creator_resource_wallet_entries AS entries
GROUP BY entries.user_id
ON CONFLICT (user_id) DO UPDATE
SET available_token_subunits = EXCLUDED.available_token_subunits,
    lifetime_earned_token_subunits = EXCLUDED.lifetime_earned_token_subunits,
    lifetime_refunded_token_subunits = EXCLUDED.lifetime_refunded_token_subunits,
    updated_at = EXCLUDED.updated_at;

WITH bundle_totals AS (
  SELECT
    bundles.id AS bundle_id,
    coalesce(sum(entries.gross_token_units), 0)::bigint AS gross_tokens,
    coalesce(sum(entries.creator_amount_token_subunits), 0)::bigint AS creator_subunits,
    coalesce(sum(entries.platform_fee_token_subunits), 0)::bigint AS platform_subunits
  FROM public.post_resource_bundles AS bundles
  LEFT JOIN public.creator_resource_wallet_entries AS entries
    ON entries.bundle_id = bundles.id
  GROUP BY bundles.id
)
UPDATE public.post_resource_bundles AS bundles
SET gross_sales_tokens = totals.gross_tokens,
    creator_earnings_token_subunits = totals.creator_subunits,
    platform_fee_token_subunits = totals.platform_subunits,
    earnings_usd_cents = floor(totals.creator_subunits::numeric / 100)::integer
FROM bundle_totals AS totals
WHERE totals.bundle_id = bundles.id;

CREATE OR REPLACE FUNCTION public.apply_post_resource_wallet_purchase_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_owner_user_id uuid;
  v_entry_id bigint;
  v_creator_subunits bigint;
  v_platform_subunits bigint;
BEGIN
  IF NEW.price_usd_cents <= 0 THEN
    RETURN NEW;
  END IF;

  SELECT owner_user_id
  INTO v_owner_user_id
  FROM public.post_resource_bundles
  WHERE id = NEW.bundle_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Resource bundle not found for creator settlement';
  END IF;

  v_creator_subunits := NEW.price_usd_cents::bigint * 85;
  v_platform_subunits := NEW.price_usd_cents::bigint * 15;

  INSERT INTO public.creator_resource_wallet_entries (
    event_key,
    user_id,
    bundle_id,
    purchase_id,
    order_id,
    entry_kind,
    gross_token_units,
    creator_amount_token_subunits,
    platform_fee_token_subunits
  ) VALUES (
    'purchase:' || NEW.id::text,
    v_owner_user_id,
    NEW.bundle_id,
    NEW.id,
    NEW.order_id,
    'sale',
    NEW.price_usd_cents,
    v_creator_subunits,
    v_platform_subunits
  )
  ON CONFLICT (event_key) DO NOTHING
  RETURNING id INTO v_entry_id;

  IF v_entry_id IS NOT NULL THEN
    INSERT INTO public.creator_resource_wallets (
      user_id,
      available_token_subunits,
      lifetime_earned_token_subunits
    ) VALUES (
      v_owner_user_id,
      v_creator_subunits,
      v_creator_subunits
    )
    ON CONFLICT (user_id) DO UPDATE
    SET available_token_subunits = creator_resource_wallets.available_token_subunits
          + EXCLUDED.available_token_subunits,
        lifetime_earned_token_subunits = creator_resource_wallets.lifetime_earned_token_subunits
          + EXCLUDED.lifetime_earned_token_subunits,
        updated_at = timezone('utc'::text, now());

    UPDATE public.post_resource_bundles
    SET gross_sales_tokens = gross_sales_tokens + NEW.price_usd_cents,
        creator_earnings_token_subunits = creator_earnings_token_subunits + v_creator_subunits,
        platform_fee_token_subunits = platform_fee_token_subunits + v_platform_subunits,
        updated_at = timezone('utc'::text, now())
    WHERE id = NEW.bundle_id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS post_resource_purchase_creator_settlement
  ON public.post_resource_bundle_purchases;
CREATE TRIGGER post_resource_purchase_creator_settlement
AFTER INSERT ON public.post_resource_bundle_purchases
FOR EACH ROW
EXECUTE FUNCTION public.apply_post_resource_wallet_purchase_change();

CREATE OR REPLACE FUNCTION public.reverse_post_resource_wallet_on_refund()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_sale public.creator_resource_wallet_entries%ROWTYPE;
  v_entry_id bigint;
BEGIN
  IF OLD.status <> 'paid' OR NEW.status <> 'failed' THEN
    RETURN NEW;
  END IF;

  -- Account or post deletion removes orders rather than transitioning them.
  -- A paid-to-failed transition only reverses settlement after the entitlement
  -- row has actually been removed by the authoritative refund transaction.
  IF EXISTS (
    SELECT 1
    FROM public.post_resource_bundle_purchases
    WHERE order_id = NEW.id
  ) THEN
    RETURN NEW;
  END IF;

  SELECT entries.*
  INTO v_sale
  FROM public.creator_resource_wallet_entries AS entries
  WHERE entries.order_id = NEW.id
    AND entries.entry_kind = 'sale'
    AND NOT EXISTS (
      SELECT 1
      FROM public.creator_resource_wallet_entries AS refunds
      WHERE refunds.event_key = 'refund-purchase:' || entries.purchase_id::text
    )
  ORDER BY entries.id DESC
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.creator_resource_wallet_entries (
    event_key,
    user_id,
    bundle_id,
    purchase_id,
    order_id,
    entry_kind,
    gross_token_units,
    creator_amount_token_subunits,
    platform_fee_token_subunits
  ) VALUES (
    'refund-purchase:' || v_sale.purchase_id::text,
    v_sale.user_id,
    v_sale.bundle_id,
    v_sale.purchase_id,
    NEW.id,
    'refund',
    v_sale.gross_token_units,
    -v_sale.creator_amount_token_subunits,
    -v_sale.platform_fee_token_subunits
  )
  ON CONFLICT (event_key) DO NOTHING
  RETURNING id INTO v_entry_id;

  IF v_entry_id IS NOT NULL THEN
    UPDATE public.creator_resource_wallets
    SET available_token_subunits = available_token_subunits
          - v_sale.creator_amount_token_subunits,
        lifetime_refunded_token_subunits = lifetime_refunded_token_subunits
          + v_sale.creator_amount_token_subunits,
        updated_at = timezone('utc'::text, now())
    WHERE user_id = v_sale.user_id;

    UPDATE public.post_resource_bundles
    SET gross_sales_tokens = greatest(
          0,
          gross_sales_tokens - v_sale.gross_token_units
        ),
        creator_earnings_token_subunits = greatest(
          0,
          creator_earnings_token_subunits - v_sale.creator_amount_token_subunits
        ),
        platform_fee_token_subunits = greatest(
          0,
          platform_fee_token_subunits - v_sale.platform_fee_token_subunits
        ),
        updated_at = timezone('utc'::text, now())
    WHERE id = v_sale.bundle_id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS post_resource_order_creator_refund
  ON public.post_resource_bundle_orders;
CREATE TRIGGER post_resource_order_creator_refund
AFTER UPDATE OF status ON public.post_resource_bundle_orders
FOR EACH ROW
EXECUTE FUNCTION public.reverse_post_resource_wallet_on_refund();

-- Existing purchase functions update the legacy earnings column with gross
-- price after inserting/deleting an entitlement. Keep those callers backward
-- compatible while ensuring the legacy projection always reflects net creator
-- proceeds from the exact ledger.
CREATE OR REPLACE FUNCTION public.normalize_post_resource_legacy_earnings()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  NEW.earnings_usd_cents := floor(
    NEW.creator_earnings_token_subunits::numeric / 100
  )::integer;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS post_resource_bundle_normalize_legacy_earnings
  ON public.post_resource_bundles;
CREATE TRIGGER post_resource_bundle_normalize_legacy_earnings
BEFORE UPDATE OF earnings_usd_cents, creator_earnings_token_subunits
ON public.post_resource_bundles
FOR EACH ROW
EXECUTE FUNCTION public.normalize_post_resource_legacy_earnings();

REVOKE ALL ON FUNCTION public.apply_post_resource_wallet_purchase_change()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.reverse_post_resource_wallet_on_refund()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.normalize_post_resource_legacy_earnings()
  FROM PUBLIC, anon, authenticated;
