-- Backend-owned public search documents for creators and community posts.
-- Marketplace recipes keep using marketplace_bundle_search_documents.

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA extensions;

CREATE TABLE public.post_search_documents (
  post_id uuid PRIMARY KEY REFERENCES public.posts(id) ON DELETE CASCADE,
  creator_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title_normalized text NOT NULL,
  tool_normalized text NOT NULL,
  search_text text NOT NULL,
  search_vector tsvector NOT NULL,
  created_at timestamptz NOT NULL
);

CREATE INDEX post_search_documents_vector_idx
  ON public.post_search_documents USING gin (search_vector);
CREATE INDEX post_search_documents_text_trgm_idx
  ON public.post_search_documents USING gin (search_text extensions.gin_trgm_ops);
CREATE INDEX post_search_documents_title_trgm_idx
  ON public.post_search_documents USING gin (title_normalized extensions.gin_trgm_ops);
CREATE INDEX post_search_documents_tool_trgm_idx
  ON public.post_search_documents USING gin (tool_normalized extensions.gin_trgm_ops);
CREATE INDEX post_search_documents_creator_idx
  ON public.post_search_documents (creator_user_id, post_id);

ALTER TABLE public.post_search_documents ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.post_search_documents FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.post_search_documents TO service_role;

COMMENT ON TABLE public.post_search_documents IS
  'Backend-owned, trigger-maintained search projection of moderation-clean public posts.';

CREATE TABLE public.creator_search_documents (
  creator_user_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  username text NOT NULL,
  username_normalized text NOT NULL,
  display_name text NOT NULL,
  display_name_normalized text NOT NULL,
  bio text,
  avatar_url text,
  search_text text NOT NULL,
  search_vector tsvector NOT NULL,
  public_post_count integer NOT NULL DEFAULT 0 CHECK (public_post_count >= 0),
  latest_public_post_at timestamptz
);

CREATE INDEX creator_search_documents_vector_idx
  ON public.creator_search_documents USING gin (search_vector);
CREATE INDEX creator_search_documents_username_trgm_idx
  ON public.creator_search_documents USING gin (username_normalized extensions.gin_trgm_ops);
CREATE INDEX creator_search_documents_display_name_trgm_idx
  ON public.creator_search_documents USING gin (display_name_normalized extensions.gin_trgm_ops);

ALTER TABLE public.creator_search_documents ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.creator_search_documents FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.creator_search_documents TO service_role;

COMMENT ON TABLE public.creator_search_documents IS
  'Backend-owned creator discovery projection. Empty autogenerated profiles are excluded.';

CREATE OR REPLACE FUNCTION public.refresh_post_search_documents(p_post_ids uuid[])
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  IF p_post_ids IS NULL OR cardinality(p_post_ids) = 0 THEN
    RETURN;
  END IF;

  DELETE FROM public.post_search_documents
  WHERE post_id = ANY (p_post_ids);

  INSERT INTO public.post_search_documents (
    post_id,
    creator_user_id,
    title_normalized,
    tool_normalized,
    search_text,
    search_vector,
    created_at
  )
  SELECT
    posts.id,
    posts.user_id,
    lower(btrim(coalesce(posts.title, ''))),
    lower(btrim(concat_ws(' ', posts.source_tool, posts.source_tool_slug))),
    lower(btrim(concat_ws(
      ' ',
      posts.title,
      posts.body,
      posts.prompt,
      posts.source_tool,
      posts.source_tool_slug
    ))),
    setweight(to_tsvector('simple', coalesce(posts.title, '')), 'A')
      || setweight(to_tsvector('simple', coalesce(posts.body, '')), 'B')
      || setweight(to_tsvector('simple', coalesce(posts.prompt, '')), 'B')
      || setweight(to_tsvector(
        'simple',
        concat_ws(' ', posts.source_tool, posts.source_tool_slug)
      ), 'C'),
    posts.created_at
  FROM public.posts AS posts
  WHERE posts.id = ANY (p_post_ids)
    AND posts.visibility = 'public'
    AND posts.archived_at IS NULL
    AND posts.review_status = 'visible';
END;
$function$;

REVOKE ALL ON FUNCTION public.refresh_post_search_documents(uuid[]) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.refresh_post_search_documents(uuid[]) TO service_role;

CREATE OR REPLACE FUNCTION public.refresh_creator_search_documents(p_creator_ids uuid[])
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  IF p_creator_ids IS NULL OR cardinality(p_creator_ids) = 0 THEN
    RETURN;
  END IF;

  DELETE FROM public.creator_search_documents
  WHERE creator_user_id = ANY (p_creator_ids);

  INSERT INTO public.creator_search_documents (
    creator_user_id,
    username,
    username_normalized,
    display_name,
    display_name_normalized,
    bio,
    avatar_url,
    search_text,
    search_vector,
    public_post_count,
    latest_public_post_at
  )
  SELECT
    profiles.id,
    profiles.username,
    lower(btrim(profiles.username)),
    coalesce(nullif(btrim(profiles.display_name), ''), profiles.username),
    lower(coalesce(nullif(btrim(profiles.display_name), ''), profiles.username)),
    nullif(btrim(profiles.bio), ''),
    profiles.avatar_url,
    lower(btrim(concat_ws(' ', profiles.username, profiles.display_name, profiles.bio))),
    setweight(to_tsvector('simple', coalesce(profiles.username, '')), 'A')
      || setweight(to_tsvector('simple', coalesce(profiles.display_name, '')), 'A')
      || setweight(to_tsvector('simple', coalesce(profiles.bio, '')), 'C'),
    post_stats.public_post_count,
    post_stats.latest_public_post_at
  FROM public.profiles AS profiles
  CROSS JOIN LATERAL (
    SELECT
      count(*)::integer AS public_post_count,
      max(posts.created_at) AS latest_public_post_at
    FROM public.posts AS posts
    WHERE posts.user_id = profiles.id
      AND posts.visibility = 'public'
      AND posts.archived_at IS NULL
      AND posts.review_status = 'visible'
  ) AS post_stats
  WHERE profiles.id = ANY (p_creator_ids)
    AND profiles.username IS NOT NULL
    AND (
      profiles.username !~ '^creator-[0-9a-f]{8}$'
      OR post_stats.public_post_count > 0
    );
END;
$function$;

REVOKE ALL ON FUNCTION public.refresh_creator_search_documents(uuid[]) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.refresh_creator_search_documents(uuid[]) TO service_role;

CREATE OR REPLACE FUNCTION public.trg_refresh_post_search_document()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  PERFORM public.refresh_post_search_documents(ARRAY[NEW.id]);
  RETURN NULL;
END;
$function$;

CREATE OR REPLACE FUNCTION public.trg_refresh_creator_search_profile()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  PERFORM public.refresh_creator_search_documents(ARRAY[NEW.id]);
  RETURN NULL;
END;
$function$;

CREATE OR REPLACE FUNCTION public.trg_refresh_creator_search_for_post()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_creator_ids uuid[];
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_creator_ids := ARRAY[OLD.user_id];
  ELSIF TG_OP = 'INSERT' THEN
    v_creator_ids := ARRAY[NEW.user_id];
  ELSE
    v_creator_ids := ARRAY[OLD.user_id, NEW.user_id];
  END IF;

  PERFORM public.refresh_creator_search_documents(
    ARRAY(
      SELECT DISTINCT ids.creator_id
      FROM unnest(v_creator_ids) AS ids(creator_id)
      WHERE ids.creator_id IS NOT NULL
    )
  );
  RETURN NULL;
END;
$function$;

REVOKE ALL ON FUNCTION public.trg_refresh_post_search_document() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.trg_refresh_creator_search_profile() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.trg_refresh_creator_search_for_post() FROM PUBLIC, anon, authenticated;

CREATE TRIGGER posts_refresh_public_search_document
AFTER INSERT OR UPDATE OF
  title, body, prompt, source_tool, source_tool_slug, visibility, archived_at, review_status
ON public.posts
FOR EACH ROW EXECUTE FUNCTION public.trg_refresh_post_search_document();

CREATE TRIGGER profiles_refresh_public_search_document
AFTER INSERT OR UPDATE OF username, display_name, bio, avatar_url
ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.trg_refresh_creator_search_profile();

CREATE TRIGGER posts_refresh_creator_search_document
AFTER INSERT OR DELETE OR UPDATE OF user_id, visibility, archived_at, review_status, created_at
ON public.posts
FOR EACH ROW EXECUTE FUNCTION public.trg_refresh_creator_search_for_post();

CREATE OR REPLACE FUNCTION public.search_public_creators(
  p_query text,
  p_viewer_user_id uuid DEFAULT NULL,
  p_after_score double precision DEFAULT NULL,
  p_after_id uuid DEFAULT NULL,
  p_limit integer DEFAULT 20
)
RETURNS TABLE(
  creator_user_id uuid,
  username text,
  display_name text,
  bio text,
  avatar_url text,
  public_post_count integer,
  is_following boolean,
  search_score double precision
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_query text := lower(btrim(regexp_replace(coalesce(p_query, ''), '[[:space:]]+', ' ', 'g')));
  -- LIKE/ILIKE patterns are built by concatenation, so pattern metacharacters
  -- in user input must match literally: '%%' must not become match-everything.
  v_like text;
BEGIN
  IF char_length(v_query) < 2 OR char_length(v_query) > 100 THEN
    RAISE EXCEPTION 'Creator search query must contain between 2 and 100 characters';
  END IF;
  v_like := replace(replace(replace(v_query, '\', '\\'), '%', '\%'), '_', '\_');
  IF p_limit < 1 OR p_limit > 25 THEN
    RAISE EXCEPTION 'Creator search limit must be between 1 and 25';
  END IF;
  IF p_after_score IS NOT NULL AND p_after_id IS NULL THEN
    RAISE EXCEPTION 'Creator search cursor is incomplete';
  END IF;

  RETURN QUERY
  WITH scored AS (
    SELECT
      documents.creator_user_id,
      documents.username,
      documents.display_name,
      documents.bio,
      documents.avatar_url,
      documents.public_post_count,
      EXISTS (
        SELECT 1
        FROM public.follows
        WHERE follower_id = p_viewer_user_id
          AND following_id = documents.creator_user_id
      ) AS is_following,
      (
        CASE WHEN documents.username_normalized = v_query THEN 10.0 ELSE 0.0 END
        + CASE WHEN documents.username_normalized LIKE v_like || '%' THEN 5.0 ELSE 0.0 END
        + CASE WHEN documents.display_name_normalized = v_query THEN 6.0 ELSE 0.0 END
        + CASE WHEN documents.display_name_normalized LIKE v_like || '%' THEN 3.0 ELSE 0.0 END
        + ts_rank_cd(documents.search_vector, plainto_tsquery('simple', v_query)) * 2.0
        + greatest(
          extensions.similarity(documents.username_normalized, v_query),
          extensions.similarity(documents.display_name_normalized, v_query)
        ) * 1.5
        + CASE WHEN EXISTS (
          SELECT 1
          FROM public.follows
          WHERE follower_id = p_viewer_user_id
            AND following_id = documents.creator_user_id
        ) THEN 0.25 ELSE 0.0 END
        + least(0.5, ln(1 + documents.public_post_count) * 0.08)
      )::double precision AS search_score
    FROM public.creator_search_documents AS documents
    WHERE documents.username_normalized LIKE v_like || '%'
      OR documents.display_name_normalized LIKE v_like || '%'
      OR documents.search_vector @@ plainto_tsquery('simple', v_query)
      OR documents.username_normalized OPERATOR(extensions.%) v_query
      OR documents.display_name_normalized OPERATOR(extensions.%) v_query
  )
  SELECT
    scored.creator_user_id,
    scored.username,
    scored.display_name,
    scored.bio,
    scored.avatar_url,
    scored.public_post_count,
    scored.is_following,
    scored.search_score
  FROM scored
  WHERE p_after_score IS NULL
    OR scored.search_score < p_after_score
    OR (scored.search_score = p_after_score AND scored.creator_user_id > p_after_id)
  ORDER BY scored.search_score DESC, scored.creator_user_id ASC
  LIMIT p_limit;
END;
$function$;

CREATE OR REPLACE FUNCTION public.search_public_posts(
  p_query text,
  p_viewer_user_id uuid DEFAULT NULL,
  p_after_score double precision DEFAULT NULL,
  p_after_id uuid DEFAULT NULL,
  p_limit integer DEFAULT 20
)
RETURNS TABLE(
  post_id uuid,
  creator_user_id uuid,
  search_score double precision
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_query text := lower(btrim(regexp_replace(coalesce(p_query, ''), '[[:space:]]+', ' ', 'g')));
  -- Same literal-matching rule as creator search: a query of '%%%' must not
  -- become an ILIKE full scan over every post document.
  v_like text;
BEGIN
  IF char_length(v_query) < 3 OR char_length(v_query) > 100 THEN
    RAISE EXCEPTION 'Post search query must contain between 3 and 100 characters';
  END IF;
  v_like := replace(replace(replace(v_query, '\', '\\'), '%', '\%'), '_', '\_');
  IF p_limit < 1 OR p_limit > 25 THEN
    RAISE EXCEPTION 'Post search limit must be between 1 and 25';
  END IF;
  IF p_after_score IS NOT NULL AND p_after_id IS NULL THEN
    RAISE EXCEPTION 'Post search cursor is incomplete';
  END IF;

  RETURN QUERY
  WITH scored AS (
    SELECT
      documents.post_id,
      documents.creator_user_id,
      (
        CASE WHEN documents.title_normalized = v_query THEN 10.0 ELSE 0.0 END
        + CASE WHEN documents.title_normalized LIKE v_like || '%' THEN 5.0 ELSE 0.0 END
        + CASE WHEN documents.tool_normalized = v_query THEN 3.0 ELSE 0.0 END
        + ts_rank_cd(documents.search_vector, plainto_tsquery('simple', v_query)) * 2.5
        + greatest(
          extensions.similarity(documents.title_normalized, v_query),
          extensions.similarity(documents.tool_normalized, v_query)
        ) * 1.5
        + CASE WHEN EXISTS (
          SELECT 1
          FROM public.follows
          WHERE follower_id = p_viewer_user_id
            AND following_id = documents.creator_user_id
        ) THEN 0.2 ELSE 0.0 END
        + least(
          0.35,
          ln(1 + posts.save_count + posts.comment_count + posts.remix_count) * 0.04
        )
        + extract(epoch FROM documents.created_at) / 100000000000.0
      )::double precision AS search_score
    FROM public.post_search_documents AS documents
    JOIN public.posts AS posts ON posts.id = documents.post_id
    WHERE documents.search_vector @@ plainto_tsquery('simple', v_query)
      OR documents.search_text ILIKE ('%' || v_like || '%')
      OR documents.title_normalized OPERATOR(extensions.%) v_query
      OR documents.tool_normalized OPERATOR(extensions.%) v_query
  )
  SELECT scored.post_id, scored.creator_user_id, scored.search_score
  FROM scored
  WHERE p_after_score IS NULL
    OR scored.search_score < p_after_score
    OR (scored.search_score = p_after_score AND scored.post_id > p_after_id)
  ORDER BY scored.search_score DESC, scored.post_id ASC
  LIMIT p_limit;
END;
$function$;

REVOKE ALL ON FUNCTION public.search_public_creators(text, uuid, double precision, uuid, integer)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.search_public_posts(text, uuid, double precision, uuid, integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.search_public_creators(text, uuid, double precision, uuid, integer)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.search_public_posts(text, uuid, double precision, uuid, integer)
  TO service_role;

SELECT public.refresh_post_search_documents(array_agg(id)) FROM public.posts;
SELECT public.refresh_creator_search_documents(array_agg(id)) FROM public.profiles;
